/**
 * MicroService Bus rest API
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2016-2017 ZTE Corporation.
 * Modifications Copyright 2017 Huawei Technologies Co., Ltd.
 */


package org.openo.sdno.lcm.restclient.msb.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * HttpMetrics
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-20T12:04:17.236Z")
public class HttpMetrics   {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("max")
  private Double max = null;

  @JsonProperty("mean")
  private Double mean = null;

  @JsonProperty("min")
  private Double min = null;

  @JsonProperty("p50")
  private Double p50 = null;

  @JsonProperty("p75")
  private Double p75 = null;

  @JsonProperty("p95")
  private Double p95 = null;

  @JsonProperty("p98")
  private Double p98 = null;

  @JsonProperty("p99")
  private Double p99 = null;

  @JsonProperty("p999")
  private Double p999 = null;

  @JsonProperty("stddev")
  private Double stddev = null;

  @JsonProperty("m15_rate")
  private Double m15Rate = null;

  @JsonProperty("m1_rate")
  private Double m1Rate = null;

  @JsonProperty("m5_rate")
  private Double m5Rate = null;

  @JsonProperty("mean_rate")
  private Double meanRate = null;

  @JsonProperty("duration_units")
  private String durationUnits = null;

  @JsonProperty("rate_units")
  private String rateUnits = null;

  public HttpMetrics count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public HttpMetrics max(Double max) {
    this.max = max;
    return this;
  }

   /**
   * Get max
   * @return max
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getMax() {
    return max;
  }

  public void setMax(Double max) {
    this.max = max;
  }

  public HttpMetrics mean(Double mean) {
    this.mean = mean;
    return this;
  }

   /**
   * Get mean
   * @return mean
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getMean() {
    return mean;
  }

  public void setMean(Double mean) {
    this.mean = mean;
  }

  public HttpMetrics min(Double min) {
    this.min = min;
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getMin() {
    return min;
  }

  public void setMin(Double min) {
    this.min = min;
  }

  public HttpMetrics p50(Double p50) {
    this.p50 = p50;
    return this;
  }

   /**
   * Get p50
   * @return p50
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP50() {
    return p50;
  }

  public void setP50(Double p50) {
    this.p50 = p50;
  }

  public HttpMetrics p75(Double p75) {
    this.p75 = p75;
    return this;
  }

   /**
   * Get p75
   * @return p75
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP75() {
    return p75;
  }

  public void setP75(Double p75) {
    this.p75 = p75;
  }

  public HttpMetrics p95(Double p95) {
    this.p95 = p95;
    return this;
  }

   /**
   * Get p95
   * @return p95
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP95() {
    return p95;
  }

  public void setP95(Double p95) {
    this.p95 = p95;
  }

  public HttpMetrics p98(Double p98) {
    this.p98 = p98;
    return this;
  }

   /**
   * Get p98
   * @return p98
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP98() {
    return p98;
  }

  public void setP98(Double p98) {
    this.p98 = p98;
  }

  public HttpMetrics p99(Double p99) {
    this.p99 = p99;
    return this;
  }

   /**
   * Get p99
   * @return p99
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP99() {
    return p99;
  }

  public void setP99(Double p99) {
    this.p99 = p99;
  }

  public HttpMetrics p999(Double p999) {
    this.p999 = p999;
    return this;
  }

   /**
   * Get p999
   * @return p999
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getP999() {
    return p999;
  }

  public void setP999(Double p999) {
    this.p999 = p999;
  }

  public HttpMetrics stddev(Double stddev) {
    this.stddev = stddev;
    return this;
  }

   /**
   * Get stddev
   * @return stddev
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getStddev() {
    return stddev;
  }

  public void setStddev(Double stddev) {
    this.stddev = stddev;
  }

  public HttpMetrics m15Rate(Double m15Rate) {
    this.m15Rate = m15Rate;
    return this;
  }

   /**
   * Get m15Rate
   * @return m15Rate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getM15Rate() {
    return m15Rate;
  }

  public void setM15Rate(Double m15Rate) {
    this.m15Rate = m15Rate;
  }

  public HttpMetrics m1Rate(Double m1Rate) {
    this.m1Rate = m1Rate;
    return this;
  }

   /**
   * Get m1Rate
   * @return m1Rate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getM1Rate() {
    return m1Rate;
  }

  public void setM1Rate(Double m1Rate) {
    this.m1Rate = m1Rate;
  }

  public HttpMetrics m5Rate(Double m5Rate) {
    this.m5Rate = m5Rate;
    return this;
  }

   /**
   * Get m5Rate
   * @return m5Rate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getM5Rate() {
    return m5Rate;
  }

  public void setM5Rate(Double m5Rate) {
    this.m5Rate = m5Rate;
  }

  public HttpMetrics meanRate(Double meanRate) {
    this.meanRate = meanRate;
    return this;
  }

   /**
   * Get meanRate
   * @return meanRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getMeanRate() {
    return meanRate;
  }

  public void setMeanRate(Double meanRate) {
    this.meanRate = meanRate;
  }

  public HttpMetrics durationUnits(String durationUnits) {
    this.durationUnits = durationUnits;
    return this;
  }

   /**
   * Get durationUnits
   * @return durationUnits
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDurationUnits() {
    return durationUnits;
  }

  public void setDurationUnits(String durationUnits) {
    this.durationUnits = durationUnits;
  }

  public HttpMetrics rateUnits(String rateUnits) {
    this.rateUnits = rateUnits;
    return this;
  }

   /**
   * Get rateUnits
   * @return rateUnits
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRateUnits() {
    return rateUnits;
  }

  public void setRateUnits(String rateUnits) {
    this.rateUnits = rateUnits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpMetrics httpMetrics = (HttpMetrics) o;
    return Objects.equals(this.count, httpMetrics.count) &&
        Objects.equals(this.max, httpMetrics.max) &&
        Objects.equals(this.mean, httpMetrics.mean) &&
        Objects.equals(this.min, httpMetrics.min) &&
        Objects.equals(this.p50, httpMetrics.p50) &&
        Objects.equals(this.p75, httpMetrics.p75) &&
        Objects.equals(this.p95, httpMetrics.p95) &&
        Objects.equals(this.p98, httpMetrics.p98) &&
        Objects.equals(this.p99, httpMetrics.p99) &&
        Objects.equals(this.p999, httpMetrics.p999) &&
        Objects.equals(this.stddev, httpMetrics.stddev) &&
        Objects.equals(this.m15Rate, httpMetrics.m15Rate) &&
        Objects.equals(this.m1Rate, httpMetrics.m1Rate) &&
        Objects.equals(this.m5Rate, httpMetrics.m5Rate) &&
        Objects.equals(this.meanRate, httpMetrics.meanRate) &&
        Objects.equals(this.durationUnits, httpMetrics.durationUnits) &&
        Objects.equals(this.rateUnits, httpMetrics.rateUnits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, max, mean, min, p50, p75, p95, p98, p99, p999, stddev, m15Rate, m1Rate, m5Rate, meanRate, durationUnits, rateUnits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpMetrics {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    mean: ").append(toIndentedString(mean)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    p50: ").append(toIndentedString(p50)).append("\n");
    sb.append("    p75: ").append(toIndentedString(p75)).append("\n");
    sb.append("    p95: ").append(toIndentedString(p95)).append("\n");
    sb.append("    p98: ").append(toIndentedString(p98)).append("\n");
    sb.append("    p99: ").append(toIndentedString(p99)).append("\n");
    sb.append("    p999: ").append(toIndentedString(p999)).append("\n");
    sb.append("    stddev: ").append(toIndentedString(stddev)).append("\n");
    sb.append("    m15Rate: ").append(toIndentedString(m15Rate)).append("\n");
    sb.append("    m1Rate: ").append(toIndentedString(m1Rate)).append("\n");
    sb.append("    m5Rate: ").append(toIndentedString(m5Rate)).append("\n");
    sb.append("    meanRate: ").append(toIndentedString(meanRate)).append("\n");
    sb.append("    durationUnits: ").append(toIndentedString(durationUnits)).append("\n");
    sb.append("    rateUnits: ").append(toIndentedString(rateUnits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

