/**
 * MicroService Bus rest API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.openo.sdno.lcm.restclient.msb.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openo.sdno.lcm.restclient.msb.model.Node;


/**
 * MicroServiceInfo
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-20T12:04:17.236Z")
public class MicroServiceInfo   {
  @JsonProperty("serviceName")
  private String serviceName = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("url")
  private String url = null;

  /**
   * Service Protocol
   */
  public enum ProtocolEnum {
    REST("REST"),
    
    UI("UI"),
    
    MQ("MQ"),
    
    FTP("FTP"),
    
    SNMP("SNMP"),
    
    TCP("TCP"),
    
    UDP("UDP");

    private String value;

    ProtocolEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("protocol")
  private ProtocolEnum protocol = null;

  /**
   * [visual Range]interSystem:0,inSystem:1
   */
  public enum VisualRangeEnum {
    _0("0"),
    
    _1("1");

    private String value;

    VisualRangeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("visualRange")
  private VisualRangeEnum visualRange = null;

  /**
   * lb policy
   */
  public enum LbPolicyEnum {
    ROUND_ROBIN("round-robin"),
    
    HASH("hash"),
    
    LEAST_CONN("least_conn");

    private String value;

    LbPolicyEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("lb_policy")
  private LbPolicyEnum lbPolicy = null;

  @JsonProperty("nodes")
  private List<Node> nodes = new ArrayList<Node>();

  public MicroServiceInfo serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public MicroServiceInfo version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "v1", value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public MicroServiceInfo url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Target Service URL,start with /
   * @return url
  **/
  @ApiModelProperty(example = "/api/serviceName/v1", required = true, value = "Target Service URL,start with /")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public MicroServiceInfo protocol(ProtocolEnum protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Service Protocol
   * @return protocol
  **/
  @ApiModelProperty(example = "REST", required = true, value = "Service Protocol")
  public ProtocolEnum getProtocol() {
    return protocol;
  }

  public void setProtocol(ProtocolEnum protocol) {
    this.protocol = protocol;
  }

  public MicroServiceInfo visualRange(VisualRangeEnum visualRange) {
    this.visualRange = visualRange;
    return this;
  }

   /**
   * [visual Range]interSystem:0,inSystem:1
   * @return visualRange
  **/
  @ApiModelProperty(example = "1", value = "[visual Range]interSystem:0,inSystem:1")
  public VisualRangeEnum getVisualRange() {
    return visualRange;
  }

  public void setVisualRange(VisualRangeEnum visualRange) {
    this.visualRange = visualRange;
  }

  public MicroServiceInfo lbPolicy(LbPolicyEnum lbPolicy) {
    this.lbPolicy = lbPolicy;
    return this;
  }

   /**
   * lb policy
   * @return lbPolicy
  **/
  @ApiModelProperty(example = "hash", value = "lb policy")
  public LbPolicyEnum getLbPolicy() {
    return lbPolicy;
  }

  public void setLbPolicy(LbPolicyEnum lbPolicy) {
    this.lbPolicy = lbPolicy;
  }

  public MicroServiceInfo nodes(List<Node> nodes) {
    this.nodes = nodes;
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Node> getNodes() {
    return nodes;
  }

  public void setNodes(List<Node> nodes) {
    this.nodes = nodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicroServiceInfo microServiceInfo = (MicroServiceInfo) o;
    return Objects.equals(this.serviceName, microServiceInfo.serviceName) &&
        Objects.equals(this.version, microServiceInfo.version) &&
        Objects.equals(this.url, microServiceInfo.url) &&
        Objects.equals(this.protocol, microServiceInfo.protocol) &&
        Objects.equals(this.visualRange, microServiceInfo.visualRange) &&
        Objects.equals(this.lbPolicy, microServiceInfo.lbPolicy) &&
        Objects.equals(this.nodes, microServiceInfo.nodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceName, version, url, protocol, visualRange, lbPolicy, nodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicroServiceInfo {\n");
    
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    visualRange: ").append(toIndentedString(visualRange)).append("\n");
    sb.append("    lbPolicy: ").append(toIndentedString(lbPolicy)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

