/**
 * MicroService Bus rest API
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2016-2017 ZTE Corporation.
 * Modifications Copyright 2017 Huawei Technologies Co., Ltd.
 */


package org.openo.sdno.lcm.restclient.msb.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openo.sdno.lcm.restclient.msb.model.HttpMetrics;


/**
 * Timers
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-20T12:04:17.236Z")
public class Timers   {
  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.addApiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.deleteApiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.getApiDocs")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.getApiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.getApiRoutes")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.getServerIP")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.ApiRouteResource.updateApiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.IuiRouteResource.addIuiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.IuiRouteResource.deleteIuiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.IuiRouteResource.getIuiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.IuiRouteResource.getIuiRoutes")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes = null;

  @JsonProperty("com.zte.ums.nfv.eco.hsif.msb.resources.IuiRouteResource.updateIuiRoute")
  private HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute = null;

  @JsonProperty("io.dropwizard.jetty.MutableServletContextHandler.get-requests")
  private HttpMetrics ioDropwizardJettyMutableServletContextHandlerGetRequests = null;

  @JsonProperty("io.dropwizard.jetty.MutableServletContextHandler.post-requests")
  private HttpMetrics ioDropwizardJettyMutableServletContextHandlerPostRequests = null;

  @JsonProperty("io.dropwizard.jetty.MutableServletContextHandler.put-requests")
  private HttpMetrics ioDropwizardJettyMutableServletContextHandlerPutRequests = null;

  @JsonProperty("io.dropwizard.jetty.MutableServletContextHandler.delete-requests")
  private HttpMetrics ioDropwizardJettyMutableServletContextHandlerDeleteRequests = null;

  @JsonProperty("io.dropwizard.jetty.MutableServletContextHandler.other-requests")
  private HttpMetrics ioDropwizardJettyMutableServletContextHandlerOtherRequests = null;

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute = comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes
   * @return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes() {
    return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes;
  }

  public Timers comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute;
    return this;
  }

   /**
   * Get comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute
   * @return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute() {
    return comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute;
  }

  public void setComZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute(HttpMetrics comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute) {
    this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute = comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute;
  }

  public Timers ioDropwizardJettyMutableServletContextHandlerGetRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerGetRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerGetRequests = ioDropwizardJettyMutableServletContextHandlerGetRequests;
    return this;
  }

   /**
   * Get ioDropwizardJettyMutableServletContextHandlerGetRequests
   * @return ioDropwizardJettyMutableServletContextHandlerGetRequests
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getIoDropwizardJettyMutableServletContextHandlerGetRequests() {
    return ioDropwizardJettyMutableServletContextHandlerGetRequests;
  }

  public void setIoDropwizardJettyMutableServletContextHandlerGetRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerGetRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerGetRequests = ioDropwizardJettyMutableServletContextHandlerGetRequests;
  }

  public Timers ioDropwizardJettyMutableServletContextHandlerPostRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerPostRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerPostRequests = ioDropwizardJettyMutableServletContextHandlerPostRequests;
    return this;
  }

   /**
   * Get ioDropwizardJettyMutableServletContextHandlerPostRequests
   * @return ioDropwizardJettyMutableServletContextHandlerPostRequests
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getIoDropwizardJettyMutableServletContextHandlerPostRequests() {
    return ioDropwizardJettyMutableServletContextHandlerPostRequests;
  }

  public void setIoDropwizardJettyMutableServletContextHandlerPostRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerPostRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerPostRequests = ioDropwizardJettyMutableServletContextHandlerPostRequests;
  }

  public Timers ioDropwizardJettyMutableServletContextHandlerPutRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerPutRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerPutRequests = ioDropwizardJettyMutableServletContextHandlerPutRequests;
    return this;
  }

   /**
   * Get ioDropwizardJettyMutableServletContextHandlerPutRequests
   * @return ioDropwizardJettyMutableServletContextHandlerPutRequests
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getIoDropwizardJettyMutableServletContextHandlerPutRequests() {
    return ioDropwizardJettyMutableServletContextHandlerPutRequests;
  }

  public void setIoDropwizardJettyMutableServletContextHandlerPutRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerPutRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerPutRequests = ioDropwizardJettyMutableServletContextHandlerPutRequests;
  }

  public Timers ioDropwizardJettyMutableServletContextHandlerDeleteRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerDeleteRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerDeleteRequests = ioDropwizardJettyMutableServletContextHandlerDeleteRequests;
    return this;
  }

   /**
   * Get ioDropwizardJettyMutableServletContextHandlerDeleteRequests
   * @return ioDropwizardJettyMutableServletContextHandlerDeleteRequests
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getIoDropwizardJettyMutableServletContextHandlerDeleteRequests() {
    return ioDropwizardJettyMutableServletContextHandlerDeleteRequests;
  }

  public void setIoDropwizardJettyMutableServletContextHandlerDeleteRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerDeleteRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerDeleteRequests = ioDropwizardJettyMutableServletContextHandlerDeleteRequests;
  }

  public Timers ioDropwizardJettyMutableServletContextHandlerOtherRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerOtherRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerOtherRequests = ioDropwizardJettyMutableServletContextHandlerOtherRequests;
    return this;
  }

   /**
   * Get ioDropwizardJettyMutableServletContextHandlerOtherRequests
   * @return ioDropwizardJettyMutableServletContextHandlerOtherRequests
  **/
  @ApiModelProperty(example = "null", value = "")
  public HttpMetrics getIoDropwizardJettyMutableServletContextHandlerOtherRequests() {
    return ioDropwizardJettyMutableServletContextHandlerOtherRequests;
  }

  public void setIoDropwizardJettyMutableServletContextHandlerOtherRequests(HttpMetrics ioDropwizardJettyMutableServletContextHandlerOtherRequests) {
    this.ioDropwizardJettyMutableServletContextHandlerOtherRequests = ioDropwizardJettyMutableServletContextHandlerOtherRequests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Timers timers = (Timers) o;
    return Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes, timers.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes) &&
        Objects.equals(this.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute, timers.comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute) &&
        Objects.equals(this.ioDropwizardJettyMutableServletContextHandlerGetRequests, timers.ioDropwizardJettyMutableServletContextHandlerGetRequests) &&
        Objects.equals(this.ioDropwizardJettyMutableServletContextHandlerPostRequests, timers.ioDropwizardJettyMutableServletContextHandlerPostRequests) &&
        Objects.equals(this.ioDropwizardJettyMutableServletContextHandlerPutRequests, timers.ioDropwizardJettyMutableServletContextHandlerPutRequests) &&
        Objects.equals(this.ioDropwizardJettyMutableServletContextHandlerDeleteRequests, timers.ioDropwizardJettyMutableServletContextHandlerDeleteRequests) &&
        Objects.equals(this.ioDropwizardJettyMutableServletContextHandlerOtherRequests, timers.ioDropwizardJettyMutableServletContextHandlerOtherRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP, comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute, comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute, comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute, comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute, comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes, comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute, ioDropwizardJettyMutableServletContextHandlerGetRequests, ioDropwizardJettyMutableServletContextHandlerPostRequests, ioDropwizardJettyMutableServletContextHandlerPutRequests, ioDropwizardJettyMutableServletContextHandlerDeleteRequests, ioDropwizardJettyMutableServletContextHandlerOtherRequests);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Timers {\n");
    
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceAddApiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceDeleteApiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiDocs)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetApiRoutes)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceGetServerIP)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesApiRouteResourceUpdateApiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceAddIuiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceDeleteIuiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoute)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceGetIuiRoutes)).append("\n");
    sb.append("    comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute: ").append(toIndentedString(comZteUmsNfvEcoHsifMsbResourcesIuiRouteResourceUpdateIuiRoute)).append("\n");
    sb.append("    ioDropwizardJettyMutableServletContextHandlerGetRequests: ").append(toIndentedString(ioDropwizardJettyMutableServletContextHandlerGetRequests)).append("\n");
    sb.append("    ioDropwizardJettyMutableServletContextHandlerPostRequests: ").append(toIndentedString(ioDropwizardJettyMutableServletContextHandlerPostRequests)).append("\n");
    sb.append("    ioDropwizardJettyMutableServletContextHandlerPutRequests: ").append(toIndentedString(ioDropwizardJettyMutableServletContextHandlerPutRequests)).append("\n");
    sb.append("    ioDropwizardJettyMutableServletContextHandlerDeleteRequests: ").append(toIndentedString(ioDropwizardJettyMutableServletContextHandlerDeleteRequests)).append("\n");
    sb.append("    ioDropwizardJettyMutableServletContextHandlerOtherRequests: ").append(toIndentedString(ioDropwizardJettyMutableServletContextHandlerOtherRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

