swagger: '2.0'
info:
  version: 1.1.0
  title: connectivity services
  description: API of connectivity services
basePath: "/openoapi/sdnomss/v1"
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  "/buckets/connectivityservicedb/resources/connectivityservice/objects":
    post:
      description: Add a new connectivity services
      operationId: createConnectivityService
      parameters:
      - in: body
        name: body
        description: the createConnectivityService to be created
        required: true
        schema:
          "$ref": "#/definitions/ConnectivityService"
      responses:
        '200':
          description: Create connectivity service success
          schema:
            "$ref": "#/definitions/ResponseConnectivityService"
        '404':
          description: Create connectivity service failure as url not found
        '500':
          description: Create connectivity service failure as internal error
    get:
      description: Add a new connectivity services
      operationId: getConnectivityService
      responses:
        '200':
          description: Get connectivity service success
          schema:
            "$ref": "#/definitions/ResponseConnectivityService"
        '404':
          description: Get connectivity service failure as url not found
        '500':
          description: Get connectivity service failure as internal error
  "/buckets/connectivityservicedb/resources/connectivityservice/objects/{id}":
    get:
      description: Read the connectivity services
      operationId: readConnectivityService
      parameters:
      - name: id
        in: path
        description: ID of the connectivity service to be deleted
        required: true
        type: string
      responses:
        '200':
          description: Get connectivity service success
          schema:
            "$ref": "#/definitions/ResponseConnectivityService"
        '404':
          description: Get connectivity service failure as url not found
        '500':
          description: Get connectivity service failure as internal error
    delete:
      description: Delete the connectivity services
      operationId: deleteConnectivityService
      parameters:
      - name: id
        in: path
        description: ID of the connectivity service to be deleted
        required: true
        type: string
      responses:
        '200':
          description: Delete connectivity service success
        '404':
          description: Delete connectivity service failure as url not found
        '500':
          description: Delete connectivity service failure as internal error
    put:
      description: modify the value.
      operationId: updateConnectivityService
      parameters:
      - name: id
        in: path
        description: ID of the connectivity service to be deleted
        required: true
        type: string
      - name: body
        in: body
        description: the partial connectivity service for the update operation
        required: true
        schema:
          "$ref": "#/definitions/UpdateConnectivityService"
      responses:
        '200':
          description: Update connectivity service success
          schema:
            "$ref": "#/definitions/UpdateResponseConnectivityService"
        '404':
          description: Update connectivity service failure as url not found
        '500':
          description: Update connectivity service failure as internal error
definitions:
  ConnectivityService:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      version:
        type: string
      adminStatus:
        type: string
      operStatus:
        type: string
      actionState:
        type: string
      statusReason:
        type: string
      ownerID:
        type: string
      tenantID:
        type: string
      location:
        type: string
      templateId:
        type: string
      lifecycleState:
        type: string
  ResponseConnectivityService:
    type: object
    properties:
      lifecycleState:
        type: string
      createtime:
        type: string
      actionState:
        type: string
      description:
        type: string
      ownerID:
        type: string
      templateId:
        type: string
      version:
        type: string
      statusReason:
        type: string
      adminStatus:
        type: string
      name:
        type: string
      operStatus:
        type: string
      tenantID:
        type: string
      location:
        type: string
      id:
        type: string
  UpdateConnectivityService:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      version:
        type: string
      adminStatus:
        type: string
      operStatus:
        type: string
      actionState:
        type: string
      statusReason:
        type: string
      ownerID:
        type: string
      tenantID:
        type: string
      location:
        type: string
      templateId:
        type: string
      lifecycleState:
        type: string
  UpdateResponseConnectivityService:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      version:
        type: string
      adminStatus:
        type: string
      operStatus:
        type: string
      actionState:
        type: string
      statusReason:
        type: string
      ownerID:
        type: string
      tenantID:
        type: string
      location:
        type: string
      templateId:
        type: string
      lifecycleState:
        type: string
