/**
 * Open-o Catalog Service rest API
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2016-2017 ZTE Corporation.
 * Modifications Copyright 2017 Huawei Technologies Co., Ltd.
 */


package org.openo.sdno.lcm.restclient.catalog.api;

import org.openo.sdno.lcm.restclient.catalog.ApiException;
import org.openo.sdno.lcm.restclient.catalog.model.CsarFileUriResponse;
import org.openo.sdno.lcm.restclient.catalog.model.PackageMeta;
import org.openo.sdno.lcm.restclient.catalog.model.UploadPackageResponse;
import org.openo.sdno.lcm.restclient.catalog.model.FormDataContentDisposition;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PackageResourceApi
 */
public class PackageResourceApiTest {

    private final PackageResourceApi api = new PackageResourceApi();

    
    /**
     * delete a package
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delPackageTest() throws ApiException {
        String csarId = null;
        // api.delPackage(csarId);

        // TODO: test validations
    }
    
    /**
     * get csar file uri by csarId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCsarFileUriTest() throws ApiException {
        String csarId = null;
        String relativePath = null;
        // CsarFileUriResponse response = api.getCsarFileUri(csarId, relativePath);

        // TODO: test validations
    }
    
    /**
     * get csar package list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryPackageByIdTest() throws ApiException {
        String csarId = null;
        // List<PackageMeta> response = api.queryPackageById(csarId);

        // TODO: test validations
    }
    
    /**
     * get csar package list by condition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryPackageListByCondTest() throws ApiException {
        String name = null;
        String provider = null;
        String version = null;
        String deletionPending = null;
        String type = null;
        // List<PackageMeta> response = api.queryPackageListByCond(name, provider, version, deletionPending, type);

        // TODO: test validations
    }
    
    /**
     * update csar package status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePackageStatusTest() throws ApiException {
        String csarId = null;
        String operationalState = null;
        String usageState = null;
        String onBoardState = null;
        String processState = null;
        String deletionPending = null;
        // api.updatePackageStatus(csarId, operationalState, usageState, onBoardState, processState, deletionPending);

        // TODO: test validations
    }
    
    /**
     * upload csar package
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadPackageTest() throws ApiException {
        File file = null;
        FormDataContentDisposition body = null;
        // UploadPackageResponse response = api.uploadPackage(file, body);

        // TODO: test validations
    }
    
}
