/**
 * Open-o Catalog Service rest API
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.openo.sdno.lcm.restclient.catalog.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PackageMeta
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-18T13:47:52.904Z")
public class PackageMeta   {
  @JsonProperty("csarId")
  private String csarId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("downloadUri")
  private String downloadUri = null;

  @JsonProperty("size")
  private String size = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("provider")
  private String provider = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("format")
  private String format = null;

  @JsonProperty("deletionPending")
  private Boolean deletionPending = false;

  @JsonProperty("createTime")
  private String createTime = null;

  @JsonProperty("modifyTime")
  private String modifyTime = null;

  /**
   * Gets or Sets operationalState
   */
  public enum OperationalStateEnum {
    ENABLED("Enabled"),
    
    DISABLED("Disabled");

    private String value;

    OperationalStateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("operationalState")
  private OperationalStateEnum operationalState = null;

  /**
   * Gets or Sets usageState
   */
  public enum UsageStateEnum {
    INUSE("InUse"),
    
    NOTINUSE("NotInUse");

    private String value;

    UsageStateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("usageState")
  private UsageStateEnum usageState = null;

  @JsonProperty("onBoardState")
  private String onBoardState = null;

  /**
   * Gets or Sets processState
   */
  public enum ProcessStateEnum {
    NORMAL("normal"),
    
    ONBOARDING("onBoarding"),
    
    ONBOARDFAILED("onBoardFailed"),
    
    DELETING("deleting"),
    
    DELETEFAILED("deleteFailed");

    private String value;

    ProcessStateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("processState")
  private ProcessStateEnum processState = null;

  public PackageMeta csarId(String csarId) {
    this.csarId = csarId;
    return this;
  }

   /**
   * Get csarId
   * @return csarId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCsarId() {
    return csarId;
  }

  public void setCsarId(String csarId) {
    this.csarId = csarId;
  }

  public PackageMeta name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageMeta downloadUri(String downloadUri) {
    this.downloadUri = downloadUri;
    return this;
  }

   /**
   * Get downloadUri
   * @return downloadUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDownloadUri() {
    return downloadUri;
  }

  public void setDownloadUri(String downloadUri) {
    this.downloadUri = downloadUri;
  }

  public PackageMeta size(String size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSize() {
    return size;
  }

  public void setSize(String size) {
    this.size = size;
  }

  public PackageMeta version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public PackageMeta provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public PackageMeta type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PackageMeta format(String format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public PackageMeta deletionPending(Boolean deletionPending) {
    this.deletionPending = deletionPending;
    return this;
  }

   /**
   * Get deletionPending
   * @return deletionPending
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDeletionPending() {
    return deletionPending;
  }

  public void setDeletionPending(Boolean deletionPending) {
    this.deletionPending = deletionPending;
  }

  public PackageMeta createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public PackageMeta modifyTime(String modifyTime) {
    this.modifyTime = modifyTime;
    return this;
  }

   /**
   * Get modifyTime
   * @return modifyTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getModifyTime() {
    return modifyTime;
  }

  public void setModifyTime(String modifyTime) {
    this.modifyTime = modifyTime;
  }

  public PackageMeta operationalState(OperationalStateEnum operationalState) {
    this.operationalState = operationalState;
    return this;
  }

   /**
   * Get operationalState
   * @return operationalState
  **/
  @ApiModelProperty(example = "null", value = "")
  public OperationalStateEnum getOperationalState() {
    return operationalState;
  }

  public void setOperationalState(OperationalStateEnum operationalState) {
    this.operationalState = operationalState;
  }

  public PackageMeta usageState(UsageStateEnum usageState) {
    this.usageState = usageState;
    return this;
  }

   /**
   * Get usageState
   * @return usageState
  **/
  @ApiModelProperty(example = "null", value = "")
  public UsageStateEnum getUsageState() {
    return usageState;
  }

  public void setUsageState(UsageStateEnum usageState) {
    this.usageState = usageState;
  }

  public PackageMeta onBoardState(String onBoardState) {
    this.onBoardState = onBoardState;
    return this;
  }

   /**
   * Get onBoardState
   * @return onBoardState
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOnBoardState() {
    return onBoardState;
  }

  public void setOnBoardState(String onBoardState) {
    this.onBoardState = onBoardState;
  }

  public PackageMeta processState(ProcessStateEnum processState) {
    this.processState = processState;
    return this;
  }

   /**
   * Get processState
   * @return processState
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProcessStateEnum getProcessState() {
    return processState;
  }

  public void setProcessState(ProcessStateEnum processState) {
    this.processState = processState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageMeta packageMeta = (PackageMeta) o;
    return Objects.equals(this.csarId, packageMeta.csarId) &&
        Objects.equals(this.name, packageMeta.name) &&
        Objects.equals(this.downloadUri, packageMeta.downloadUri) &&
        Objects.equals(this.size, packageMeta.size) &&
        Objects.equals(this.version, packageMeta.version) &&
        Objects.equals(this.provider, packageMeta.provider) &&
        Objects.equals(this.type, packageMeta.type) &&
        Objects.equals(this.format, packageMeta.format) &&
        Objects.equals(this.deletionPending, packageMeta.deletionPending) &&
        Objects.equals(this.createTime, packageMeta.createTime) &&
        Objects.equals(this.modifyTime, packageMeta.modifyTime) &&
        Objects.equals(this.operationalState, packageMeta.operationalState) &&
        Objects.equals(this.usageState, packageMeta.usageState) &&
        Objects.equals(this.onBoardState, packageMeta.onBoardState) &&
        Objects.equals(this.processState, packageMeta.processState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csarId, name, downloadUri, size, version, provider, type, format, deletionPending, createTime, modifyTime, operationalState, usageState, onBoardState, processState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageMeta {\n");
    
    sb.append("    csarId: ").append(toIndentedString(csarId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    downloadUri: ").append(toIndentedString(downloadUri)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    deletionPending: ").append(toIndentedString(deletionPending)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    modifyTime: ").append(toIndentedString(modifyTime)).append("\n");
    sb.append("    operationalState: ").append(toIndentedString(operationalState)).append("\n");
    sb.append("    usageState: ").append(toIndentedString(usageState)).append("\n");
    sb.append("    onBoardState: ").append(toIndentedString(onBoardState)).append("\n");
    sb.append("    processState: ").append(toIndentedString(processState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

