/**
 * Open-o Catalog Service rest API
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2016-2017 ZTE Corporation.
 * Modifications Copyright 2017 Huawei Technologies Co., Ltd.
 */


package org.openo.sdno.lcm.restclient.catalog.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openo.sdno.lcm.restclient.catalog.model.KeyValuePair;


/**
 * QueryRawDataCondition
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-18T13:47:52.904Z")
public class QueryRawDataCondition   {
  @JsonProperty("csarId")
  private String csarId = null;

  @JsonProperty("inputParameters")
  private List<KeyValuePair> inputParameters = new ArrayList<KeyValuePair>();

  public QueryRawDataCondition csarId(String csarId) {
    this.csarId = csarId;
    return this;
  }

   /**
   * Get csarId
   * @return csarId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCsarId() {
    return csarId;
  }

  public void setCsarId(String csarId) {
    this.csarId = csarId;
  }

  public QueryRawDataCondition inputParameters(List<KeyValuePair> inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

   /**
   * Get inputParameters
   * @return inputParameters
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<KeyValuePair> getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(List<KeyValuePair> inputParameters) {
    this.inputParameters = inputParameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRawDataCondition queryRawDataCondition = (QueryRawDataCondition) o;
    return Objects.equals(this.csarId, queryRawDataCondition.csarId) &&
        Objects.equals(this.inputParameters, queryRawDataCondition.inputParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csarId, inputParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRawDataCondition {\n");
    
    sb.append("    csarId: ").append(toIndentedString(csarId)).append("\n");
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

