/**
 * Open-o Catalog Service rest API
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2016-2017 ZTE Corporation.
 * Modifications Copyright 2017 Huawei Technologies Co., Ltd.
 */


package org.openo.sdno.lcm.restclient.catalog.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * RelationShip
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-18T13:47:52.904Z")
public class RelationShip   {
  @JsonProperty("sourceNodeName")
  private String sourceNodeName = null;

  @JsonProperty("targetNodeName")
  private String targetNodeName = null;

  @JsonProperty("sourceNodeId")
  private String sourceNodeId = null;

  @JsonProperty("targetNodeId")
  private String targetNodeId = null;

  @JsonProperty("type")
  private String type = null;

  public RelationShip sourceNodeName(String sourceNodeName) {
    this.sourceNodeName = sourceNodeName;
    return this;
  }

   /**
   * Get sourceNodeName
   * @return sourceNodeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceNodeName() {
    return sourceNodeName;
  }

  public void setSourceNodeName(String sourceNodeName) {
    this.sourceNodeName = sourceNodeName;
  }

  public RelationShip targetNodeName(String targetNodeName) {
    this.targetNodeName = targetNodeName;
    return this;
  }

   /**
   * Get targetNodeName
   * @return targetNodeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTargetNodeName() {
    return targetNodeName;
  }

  public void setTargetNodeName(String targetNodeName) {
    this.targetNodeName = targetNodeName;
  }

  public RelationShip sourceNodeId(String sourceNodeId) {
    this.sourceNodeId = sourceNodeId;
    return this;
  }

   /**
   * Get sourceNodeId
   * @return sourceNodeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceNodeId() {
    return sourceNodeId;
  }

  public void setSourceNodeId(String sourceNodeId) {
    this.sourceNodeId = sourceNodeId;
  }

  public RelationShip targetNodeId(String targetNodeId) {
    this.targetNodeId = targetNodeId;
    return this;
  }

   /**
   * Get targetNodeId
   * @return targetNodeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTargetNodeId() {
    return targetNodeId;
  }

  public void setTargetNodeId(String targetNodeId) {
    this.targetNodeId = targetNodeId;
  }

  public RelationShip type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelationShip relationShip = (RelationShip) o;
    return Objects.equals(this.sourceNodeName, relationShip.sourceNodeName) &&
        Objects.equals(this.targetNodeName, relationShip.targetNodeName) &&
        Objects.equals(this.sourceNodeId, relationShip.sourceNodeId) &&
        Objects.equals(this.targetNodeId, relationShip.targetNodeId) &&
        Objects.equals(this.type, relationShip.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceNodeName, targetNodeName, sourceNodeId, targetNodeId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelationShip {\n");
    
    sb.append("    sourceNodeName: ").append(toIndentedString(sourceNodeName)).append("\n");
    sb.append("    targetNodeName: ").append(toIndentedString(targetNodeName)).append("\n");
    sb.append("    sourceNodeId: ").append(toIndentedString(sourceNodeId)).append("\n");
    sb.append("    targetNodeId: ").append(toIndentedString(targetNodeId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

